### ISSUE TITLE
questions on notebook

### ISSUE THREAD

**Issue by metaphorz** [openai/DALL-E#13]
I just downloaded the repo to my local file system and used jupyter notebook and then opened and played the notebook. I also downloaded the encoder and decoder to the same folder for ease of loading. It says that 'preprocess' is not defined, but it seems to be. Admittedly, a bit rusty. Running Python 3.9 on Mac OSX. Also, I may be way out of line with respect to the purpose, but I was expecting to see code that took natural language input (e.g. "Show me a penguin on snow") and then DALL*E returns the provided image.

<img width="906" alt="Screen Shot 2021-02-27 at 9 51 37 PM" src="https://user-images.githubusercontent.com/3519631/109407438-65f29380-7946-11eb-85b8-0891b9b708ce.png">

_Originally posted by @metaphorz in https://github.com/openai/DALL-E/issues/5#issuecomment-787310649_

**Comment by woctezuma** [comment]
> I was expecting to see code that took natural language input (e.g. "Show me a penguin on snow") and then DALL*E returns the provided image.

The text encoder was not publicly released.

https://github.com/openai/DALL-E/issues/4

**Comment by amish-logicwind** [comment]
@woctezuma What do you mean? Can't we input a sentence and expect images as output? Forgive me, if this is silly. Please let me know.

**Comment by woctezuma** [comment]
> Can't we input a sentence and expect images as output?

You don't have access to the text encoder, so you cannot input a sentence.
