### ISSUE TITLE
Hi! It works? I for ex cant launch it. Why? Look!

### ISSUE THREAD

**Issue by mazzzai** [openai/DALL-E#18]
screens / installation

https://disk.yandex.ru/i/kCSzh6LodRkWlQ

![Снимок экрана 2021-03-03 в 16 35 14](https://user-images.githubusercontent.com/19212675/110199956-34108e00-7e6c-11eb-9ae0-e749f4676060.png)
![Снимок экрана 2021-03-03 в 16 35 30](https://user-images.githubusercontent.com/19212675/110199959-396dd880-7e6c-11eb-9cf0-fb4fcf88cb37.png)
![Сниheмок экрана 2021-03-03 в 16 35 43](https://user-images.githubusercontent.com/19212675/110199961-3d99f600-7e6c-11eb-8b77-5c2e68042399.png)

CAN You explain me what should i do here and how launch the app?

thank you in advance

**Comment by SIC98** [comment]
I think you can try https://github.com/openai/DALL-E/issues/5#issuecomment-785747581.

**Comment by fractaldna22** [comment]
https://colab.research.google.com/drive/1oA1fZP7N1uPBxwbGIvOEXbTsq2ORa9vb?usp=sharing#scrollTo=O78RfTZfh7ji
