### ISSUE TITLE
How to derive the Equation 1?

### ISSUE THREAD

**Issue by hust-nj** [openai/DALL-E#20]
How to derive the Equation 1 in the paper https://arxiv.org/abs/2102.12092
![image](https://user-images.githubusercontent.com/27663478/110326977-506f1f00-8054-11eb-9337-648d86f03ad9.png)

**Comment by adityaramesh** [comment]
This is just the variational lower bound. It's straightforward to derive from Jensen's inequality, see e.g. [this document](http://legacydirs.umiacs.umd.edu/~xyang35/files/understanding-variational-lower.pdf).

**Comment by AaronHeee** [comment]
Hi @adityaramesh, thanks for your reply! Sorry that I am still confused how to use Jensen's inequality to derive Eq 1. My attempt is listed as below, but I am blocked at the last step -- do I miss something? Looking forward to your clarification, thanks!

![image](https://user-images.githubusercontent.com/22841820/172942208-d437072c-0e5c-4921-98b5-fff6ac1236ed.png)

**Comment by kmaziarz** [comment]
Hi @AaronHeee, I'm also confused about the KL term. In particular, it seems odd that the KL term is under the expectation over `z`, as at that point all three variables (`x`, `y` and `z`) are already bound.

**Comment by finbarrtimbers** [comment]
Hey folks- I was also confused by this, so I [wrote up the derivation](https://finbarr.ca/deriving-the-dall-e-lower-bound/). I'd appreciate a second check over my math.

**Comment by j-cyoung** [comment]
> Hey folks- I was also confused by this, so I [wrote up the derivation](https://finbarr.ca/deriving-the-dall-e-lower-bound/). I'd appreciate a second check over my math.

Thanks for your sharing. But I'm confused about the exact form of distribution $q_\Phi$, which seems be either $q_\Phi(y,z|x)$ or $q_\Phi(z)$ in your derivation, while it is $q_\Phi(z|x)$ in the original formula.

**Comment by ahmdtaha** [comment]
I have been looking into this equation for sometime. I wrote my thoughts in the attached [main.pdf](https://github.com/openai/DALL-E/files/13805729/main.pdf). I believe we need to convert a single-variable distribution $q_{\phi}(z|x)$ into a multi-variable distribution $q_{\phi}(y,z|x)$ to derive this equation. Yet, I am not sure if I made the right assumptions. I hope someone look into my derivation and share some feedback.

**Comment by blackcherry88** [comment]
there is a assumption that $`y \text{, } z \text{ in } q_{\phi} \text{ are indepedent given x}`$
