### ISSUE TITLE
Why the output dimension of the decoder is 2 * output_channels which is 6, not 3 (RGB)?

### ISSUE THREAD

**Issue by nashory** [openai/DALL-E#21]
Hi, thanks for the code!

It's a simple question, I found the output dimension of decoder is set to 2 * self.output_channels, which is 6.
I expect the output dimension should be 3 (RGB).
Can you kindly explain the reason? 

Thank you in advance!

https://github.com/openai/DALL-E/blob/3381ae9a10bafe3cb1c7c9fff554565ad7751e7f/dall_e/decoder.py#L82

**Comment by vmicheli** [comment]
Hi,

The decoder does not directly compute pixel values but rather the parameters of a Logit-Laplace distribution from which the pixels are assumed to originate (see Appendix A.3 in the paper https://arxiv.org/abs/2102.12092).

**Comment by nashory** [comment]
Thank you!
