### ISSUE TITLE
Make it clear that this package does not allow full DALL-E functionality

### ISSUE THREAD

**Issue by bsmith418** [openai/DALL-E#27]
Many of us are arriving here with the expectation that we'll be able to replicate text-to-image functionality exhibited by DALL-E:
https://openai.com/blog/dall-e/

We can't. Despite naming this repo "DALL-E", you have only released a minor part of the DALL-E functionality. This isn't immediately clear.

Please make clear the limitations of this package, so people don't have to dig around and waste their time before discovering that text-to-image functionality isn't here and will never be released.

**Comment by adityaramesh** [comment]
Ok, I added the following text to the README:

>The transformer used to generate the images from the text is not part of this code release.
