### ISSUE TITLE
Will DALL-E be released as part of the API?

### ISSUE THREAD

**Issue by varkarrus** [openai/DALL-E#9]
[According to this, there's no plan to release the whole model](https://github.com/openai/DALL-E/issues/4), but will it eventually be semi-open like GPT-3?

Or will it be kept behind closed doors, forever to tantalize us with its possibilities?

**Comment by adityaramesh** [comment]
It's something we are considering

**Comment by eliohead** [comment]
Semi-openAI

**Comment by flarn2006** [comment]
Glad to finally have some word about this, even if it's nothing certain.
